name: youtube-trending-analysis

services:
  # ==========================================
  # 1. HADOOP HDFS CLUSTER (Storage data)
  # ==========================================
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870" # Web UI of HDFS
      - "9000:9000" # Internal communication port
    environment:
      - CLUSTER_NAME=youtube-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - youtube-network
    volumes:
      - namenode_data:/hadoop/dfs/name
      - ./hadoop_conf:/etc/hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - youtube-network
    volumes:
      - datanode_data:/hadoop/dfs/data
      - ./hadoop_conf:/etc/hadoop
    depends_on:
      - namenode

  # ==========================================
  # 2. CỤM HIVE (Data Warehouse & Schema)
  # ==========================================
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    networks:
      - youtube-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - SERVICE_PRECONDITION=namenode:9870 hive-metastore-postgresql:5432
    command: /opt/hive/bin/hive --service metastore
    networks:
      - youtube-network
    ports:
      - "9083:9083"
    volumes:
      - ./hadoop_conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    depends_on:
      - namenode
      - hive-metastore-postgresql

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - SERVICE_PRECONDITION=hive-metastore:9083
    ports:
      - "10000:10000" # JDBC port to connect SQL
    networks:
      - youtube-network
    volumes:
      - ./hadoop_conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    depends_on:
      - hive-metastore

  # ==========================================
  # 3. SPARK CLUSTER (Processing)
  # ==========================================
  spark-master:
    image: docker.io/apache/spark:3.5.2
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080" # Web UI of Spark Master
      - "7077:7077"
    networks:
      - youtube-network

  spark-worker:
    image: docker.io/apache/spark:3.5.2
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
    networks:
      - youtube-network
    depends_on:
      - spark-master

  # ==========================================
  # 4. JUPYTERLAB (IDE )
  # ==========================================
  jupyter-lab:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter-lab
    ports:
      - "8888:8888" # Open the browser at http://localhost:8888
      - "4040:4040" # Spark Application UI
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077
      - JUPYTER_TOKEN=youtube135
    volumes:
      - ../notebooks:/home/jovyan/notebooks
      - ../src:/home/jovyan/src
      - ../data:/home/jovyan/data
      - ../tests:/home/jovyan/tests
    networks:
      - youtube-network
    depends_on:
      - spark-master
      - hive-metastore

networks:
  youtube-network:
    driver: bridge

volumes:
  namenode_data:
  datanode_data:
  postgres_data:
